{% set name = "stardist" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stardist/stardist/archive/refs/tags/{{ version }}.tar.gz
  sha256: 271acab1bcde623dac61e1a01479376ee5f43fc19820a56acdff86a1aa4f93d0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - numpy
    - pip
    - python
    - setuptools
  run:
    - csbdeep >=0.6.3
    - numba
    - python
    - scikit-image
    - imageio
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - stardist
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/stardist/stardist
  summary: StarDist
  license: MIT
  license_file:
    - LICENSE.txt
    - stardist/lib/external/qhull_src/COPYING.txt
    - stardist/lib/external/clipper/LICENSE.txt
    - stardist/lib/external/nanoflann/LICENSE.txt

extra:
  recipe-maintainers:
    - uschmidt83
    - goanpeca
    - jaimergp
