{% set name = "stardist" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stardist/stardist/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9083c9ee81fb8389ad7262f870121e480095e6d90d1b7c3285e13908151bbda1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - numpy
    - pip
    - python
    - setuptools
  run:
    - csbdeep >=0.8.0
    - numba
    - python
    - scikit-image
    - imageio
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - stardist
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/stardist/stardist
  summary: StarDist
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - stardist/lib/external/qhull_src/COPYING.txt
    - stardist/lib/external/clipper/LICENSE.txt
    - stardist/lib/external/nanoflann/LICENSE.txt

extra:
  recipe-maintainers:
    - uschmidt83
    - goanpeca
    - jaimergp
